// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShrinkLink.UserService.Infrastructure.Data;

#nullable disable

namespace ShrinkLink.UserService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(UserServiceContext))]
    [Migration("20251126094252_AddUsersSeedData")]
    partial class AddUsersSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShrinkLink.UserService.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("ShrinkLink.UserService.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("53f72fc2-cbda-43fe-90b9-45ed571e4185"),
                            Email = "user@user.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEEl9XcH2utjEVsSK57jhoxrThtc2z0kQ1hf/0a/E7qL+HO/7K6Bkav3KfSJOeA3WHw=="
                        },
                        new
                        {
                            Id = new Guid("320c16ce-5e1c-40d6-83bb-53c7342ca773"),
                            Email = "admin@admin.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEDliq5Roxa0gkptym2OdPjNXO4oKQX8XFRjXeN+2wUUjzOE4Uo3swfvqZwljE/In/w=="
                        });
                });

            modelBuilder.Entity("ShrinkLink.UserService.Domain.Entities.UserRoleMap", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoleMap");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("53f72fc2-cbda-43fe-90b9-45ed571e4185"),
                            RoleId = 1
                        },
                        new
                        {
                            UserId = new Guid("320c16ce-5e1c-40d6-83bb-53c7342ca773"),
                            RoleId = 1
                        },
                        new
                        {
                            UserId = new Guid("320c16ce-5e1c-40d6-83bb-53c7342ca773"),
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("ShrinkLink.UserService.Domain.Entities.UserRoleMap", b =>
                {
                    b.HasOne("ShrinkLink.UserService.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShrinkLink.UserService.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
