apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: gateway-container
          image: ghcr.io/alkamal30/shrink-link/gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: Otlp__Endpoint
              value: http://alloy.monitoring.svc.cluster.local:4318
            - name: ReverseProxy__Clusters__cluster-links__Destinations__destination__Address
              value: http://link-service
            - name: ReverseProxy__Clusters__cluster-redirect__Destinations__destination__Address
              value: http://redirect-service