url: "0.0.0.0:8080"
grpc:
  url: "localhost:50051"
  useTls: false
  certificatePath: ""
redis:
  address: "localhost:6379"
  password: ""
kafka:
  brokers:
    - "localhost:9092"
  redirectAnalyticsTopic: "redirect-analytics-topic"