apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: link-service
  template:
    metadata:
      labels:
        app: link-service
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: link-service-container
          image: ghcr.io/alkamal30/shrink-link/link-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ConnectionStrings__DefaultConnection
              value: Host=postgres.postgres.svc.cluster.local;Port=5432;Database=link_service_db;Username=default_user;Password=${POSTGRES_PASSWORD}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: default-secrets
                  key: POSTGRES_PASSWORD