name: LinkService

on:
  push:
    branches: [ main ]
    paths:
      - "src/link-service/**"
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Unit Tests
    runs-on: ubuntu-latest
    steps:
      # Clone repository to VM
      - name: Checkout
        uses: actions/checkout@v4

      # Install .NET to VM
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore
        run: dotnet restore src/link-service/LinkService.csproj

  docker-publish:
    name: Build & Push Docker Image
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    outputs:
      tag: ${{ steps.meta.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/link-service
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short,prefix=sha-
            type=ref,event=pr

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/link-service/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: docker-publish
    runs-on: ubuntu-latest
    steps:
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: K3s deploy
        uses: azure/k8s-deploy@v5
        with:
          action: deploy
          manifests: |
            k8s/link-service/deployment.yaml
          images: |
            ghcr.io/${{ github.repository }}/link-service:${{ needs.docker-publish.outputs.tag }}
          kubectl-version: 'latest'